[tool.poetry]
name = "tensorboard-viewer"
version = "0.1.0"
description = "Tensorboard viewer"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.9.10"
tensorboard = "^2.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
